version: 2.1

orbs:
  node: circleci/node@4.1
  aws-s3: circleci/aws-s3@2.0

workflows:
  production_build_and_deploy:
    jobs:
      - request-testing:
          type: approval
          # requires:
          #   - node/test
      - node/test:
          version: "15.1"
          # after the node/test job completes, build the dist packages and save them to a workspace
          post-steps:
            - run: npm run build
            - aws-s3/sync:
                from: build/
                to: "s3://ma-react"
                arguments: --acl public-read
          filters:
            branches:
              only:
                - main

  development_build_and_deploy:
    jobs:
      - node/test:
          version: "15.1"
          # after the node/test job completes, build the dist packages and save them to a workspace
          post-steps:
            - run: npm run build
            - aws-s3/sync:
                from: build/
                to: "s3://prod-ma-react"
                arguments: --acl public-read
          filters:
            branches:
              only:
                - develop

  dayly_tests:
    triggers:
      - schedule:
          cron: "30,35,40,45 * * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - node/test:
          version: "15.1"
